spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/Shopping_Cart
spring.datasource.username=postgres
spring.datasource.password=Naesha@06
spring.devtools.restart.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true